version: "3.3"

services:
  webrtc-sip-gw:
    container_name: webrtc-sip-gw
    image: webrtc-sip-gw
    restart: always
    network_mode: host
    volumes:
     - ./ssl/sipgw.key:/etc/ssl/privkey.pem:ro # Can be left out when TLS is disabled
     - ./ssl/sipgw.crt:/etc/ssl/fullchain.pem:ro # Can be left out when TLS is disabled
    environment:
     - TLS_DISABLE=false # Optional, defaults to false
  
  caddy:
    build: caddy
    network_mode: host
    environment:
      - KAMAILIO_IP=172.21.1.4
    volumes:
      - /root/sip-gw/webrtc-sip-gw/data:/data # can't resolve the bound vpn ip so ig host net>